## ARQUIVO DE CONFIGURAÇÃO PARA OS AGENTES INTELIGENTES
# AQUI ESTÃO AS VARIAIVES PARA SERVIREM DE CONFIGURAÇÃO PARA OS AGENTES INTELIGENTES USAREM COMO PARAMETROS

##### LEVEL 1 - BALIZA

## TOLERÂNCIA - DADOS DE TOLERÂNCIA

_L1_tentativas = 3  # QUANTIDADE DE TENTATIVAS (DEFAULT = 3)
_L1_tempo = 45000   # TEMPO PARA ATIVAR AJUDA milisegundos (DEFAULT = 45000)
_L1_batidas = 3     # QUANTIDADE DE BATIDAS (DEFAULT = 3)

## AJUSTES - DADOS DE AJUSTE PARA O JOGO

_L1_distancia_veiculos_facil = 100      # DISTANCIA PARA AUMENTAR ENTRE OS VEICULOS DA BALIZA (DEFAULT = 100)
_L1_distancia_veiculos_dificil = -50    # DISTANCIA PARA DIMINUIR ENTRE OS VEICULOS DA BALIZA (DEFAULT = -50)
_L1_penalidade_tempo_facil = 2.5        # PENALIDADE DE TEMPO PARA CADA BATIDA (DEFAULT = 2.5)
_L1_penalidade_tempo_dificil = 6        # PENALIDADE DE TEMPO PARA CADA BATIDA (DEFAULT = 6)

##### LEVEL 2 - BALIZA COM OBSTACULOS

## TOLERANCIA - DADOS DE TOLERANCIA

_L2_tentativas = 3  # QUANTIDADE DE TENTATIVAS (DEFAULT = 3)
_L2_tempo = 40000   # TEMPO PARA ATIVAR AJUDA milisegundos (DEFAULT = 40000)
_L2_batidas = 2     # QUANTIDADE DE BATIDAS (DEFAULT = 2)

## AJUSTES - DADOS DE AJUSTE PARA O JOGO

_L2_acrescimo_tempo_facil = 10000       # ACRESCENTA TEMPO AO LIMITE DO JOGO (DEFAULT = 10000)
_L2_acrescimo_tempo_dificil = -15000    # DECREMENTA TEMPO AO LIMITE DO JOGO (DEFAULT = -15000)
_L2_penalidade_tempo_facil = 3          # PENALIDADE DE TEMPO PARA CADA BATIDA (DEFAULT = 3)
_L2_penalidade_tempo_dificil = 8        # PENALIDADE DE TEMPO PARA CADA BATIDA (DEFAULT = 8)


##### LEVEL 3 - SIMULADOR DE TRANSITO

## TOLERÂNCIA - DADOS DE TOLERÂNCIA

_L3_batidas = 5         # BATIDAS DE CARRO (DEFAULT = 5)
_L3_falha_atender = 2   # NAO ATENDER O TELEFONE (DEFAULT = 2)

## AJUSTES - DADOS DE AJUSTE

_L3_acrescimo_tempo_facil = 20000   # ACRESCENTA TEMPO AO LIMITE DO JOGO (DEFAULT = 20000)
_L3_acrescimo_tempo_dificil = -5000 # ACRESCENTA TEMPO AO LIMITE DO JOGO (DEFAULT = -5000)
_L3_ponto_atender = 200             # AJUSTE DE PONTOS AUMENTADO PARA ATENDER O CELULAR (DEFAULT = 200)
_L3_ponto_atender = 50              # AJUSTE DE PONTOS AUMENTADO PARA ATENDER O CELULAR (DEFAULT = 50)