## ARQUIVO DE CONFIGURACAO PARA OS AGENTES INTELIGENTES
# AQUI ESTAO AS VARIAIVES PARA SERVIREM DE CONFIGURACAO PARA OS AGENTES INTELIGENTES USAREM COMO PARAMETROS

##### LEVEL 1 - BALIZA

## TOLERANCIA - DADOS DE TOLERANCIA

_L1_PARAMETRO_tentativas = 3                  # QUANTIDADE DE TENTATIVAS (DEFAULT = 3)
_L1_PARAMETRO_tempo_restante = 15             # TEMPO PARA ATIVAR AJUDA segundos (DEFAULT = 15)
_L1_PARAMETRO_batidas = 3                     # QUANTIDADE DE BATIDAS (DEFAULT = 3)

## AJUSTES - DADOS DE AJUSTE PARA O JOGO

_L1_penalidade_tempo_facil = 2      # PENALIDADE DE TEMPO PARA CADA BATIDA (DEFAULT = 2.5)
_L1_penalidade_tempo_dificil = 3    # PENALIDADE DE TEMPO PARA CADA BATIDA (DEFAULT = 6)

_L1_tempo_jogo_dificil = 40         # TEMPO DE JOGO PARA O MODO DIFICIL (DEFAULT = 40)
_L1_tempo_jogo_facil = 50           # TEMPO DE JOGO PARA O MODO FACIL (DEFAULT = 60)


##### LEVEL 2 - BALIZA COM OBSTACULOS

## TOLERANCIA - DADOS DE TOLERANCIA

_L2_PARAMETRO_tentativas = 3                  # QUANTIDADE DE TENTATIVAS (DEFAULT = 3)
_L2_PARAMETRO_tempo_restante = 20             # TEMPO PARA ATIVAR AJUDA milisegundos (DEFAULT = 20)
_L2_PARAMETRO_batidas = 2                     # QUANTIDADE DE BATIDAS (DEFAULT = 2)

## AJUSTES - DADOS DE AJUSTE PARA O JOGO

_L2_tempo_jogo_dificil = 45         # TEMPO DE JOGO PARA O MODO DIFICIL (DEFAULT = 40)
_L2_tempo_jogo_facil = 60           # TEMPO DE JOGO PARA O MODO FACIL (DEFAULT = 60)

_L2_penalidade_tempo_facil = 2      # PENALIDADE DE TEMPO PARA CADA BATIDA (DEFAULT = 3)
_L2_penalidade_tempo_dificil = 4    # PENALIDADE DE TEMPO PARA CADA BATIDA (DEFAULT = 8)
