## ARQUIVO DE CONFIGURACAO PARA OS AGENTES INTELIGENTES
# AQUI ESTAO AS VARIAIVES PARA SERVIREM DE CONFIGURACAO PARA OS AGENTES INTELIGENTES USAREM COMO PARAMETROS


##### LEVEL 3 - SIMULADOR DE TRANSITO

## TOLERANCIA - DADOS DE TOLERANCIA

_L3_PARAMETRO_pontos = 500              # PONTOS PARA ATIVAR O MODO DIFICL (DEFAULT = 500)
_L3_PARAMETRO_batidas = 5               # BATIDAS DE CARRO (DEFAULT = 5)
_L3_PARAMETRO_falha_atender = 2         # NAO ATENDER O TELEFONE (DEFAULT = 2)

## AJUSTES - DADOS DE AJUSTE

_L3_ponto_atender_facil = 200           # AJUSTE DE PONTOS AUMENTADO PARA ATENDER O CELULAR (DEFAULT = 200)
_L3_ponto_atender_dificil = 120         # AJUSTE DE PONTOS AUMENTADO PARA ATENDER O CELULAR (DEFAULT = 50)

_L3_tempo_extra_facil = 15              # TEMPO EXTRA AO COLETAR O BONUS DE TEMPO (DEFAULT = 15)
_L3_tempo_extra_dificil = 10            # TEMPO EXTRA AO COLETAR O BONUS DE TEMPO (DEFAULT = 10)

_L3_quantidade_veiculos_facil = 60      # QUANTIDADE DE VEICULOS EM JOGO (DEFAULT = 60)
_L3_quantidade_veiculos_dificil = 160   # QUANTIDADE DE VEICULOS EM JOGO (DEFAULT = 160)