## ARQUIVO DE CONFIGURACAO PARA OS AGENTES INTELIGENTES
# AQUI ESTAO AS VARIAIVES PARA SERVIREM DE CONFIGURACAO PARA OS AGENTES INTELIGENTES USAREM COMO PARAMETROS


##### LEVEL 3 - SIMULADOR DE TRANSITO

## TOLERANCIA - DADOS DE TOLERANCIA

_L3_PARAMETRO_pontos = 500              # PONTOS PARA AUMENTAR A QUANTIDADE DE VEICULOS EM JOGO(DEFAULT = 500)

_L3_PARAMETRO_tempogasto = 120          # TEMPO GASTO PARA DIMINUIR A QUANTIDADE DE TEMPO EXTRA GANHO (DEFAULT = 120) SEGUNDOS

_L3_PARAMETRO_chamadas_atentidas = 4    # QUANTIDADE DE CHAMADAS ATENDIDAS PARA REDUZIR OS PONTOS GANHO (DEFAULT = 4)
_L3_PARAMETRO_paradas = 4               # QUANTIDADE DE PARADAS PARA REDUZIR OS PONTOS GANHO (DEFAULT = 4)

## AJUSTES - DADOS DE AJUSTE

_L3_quantidade_veiculos_facil = 60      # QUANTIDADE DE VEICULOS EM JOGO (DEFAULT = 60)
_L3_quantidade_veiculos_dificil = 160   # QUANTIDADE DE VEICULOS EM JOGO (DEFAULT = 160)

_L3_tempo_extra_facil = 15              # TEMPO EXTRA AO COLETAR O BONUS DE TEMPO (DEFAULT = 15)
_L3_tempo_extra_dificil = 10            # TEMPO EXTRA AO COLETAR O BONUS DE TEMPO (DEFAULT = 10)

_L3_ponto_parar_facil = 200           # AJUSTE DE PONTOS AUMENTADO PARA PARAR O CARRO (DEFAULT = 200)
_L3_ponto_parar_dificil = 170           # AJUSTE DE PONTOS AUMENTADO PARA O CARRO (DEFAULT = 170)

_L3_ponto_atender_facil = 200         # AJUSTE DE PONTOS AUMENTADO PARA ATENDER O CELULAR (DEFAULT = 200)
_L3_ponto_atender_dificil = 120         # AJUSTE DE PONTOS AUMENTADO PARA ATENDER O CELULAR (DEFAULT = 120)


