## ARQUIVO DE CONFIGURACAO PARA OS AGENTES INTELIGENTES
# AQUI ESTAO AS VARIAIVES PARA SERVIREM DE CONFIGURACAO PARA OS AGENTES INTELIGENTES USAREM COMO PARAMETROS


##### LEVEL 3 - SIMULADOR DE TRANSITO

## TOLERANCIA - DADOS DE TOLERANCIA

_L3_PARAMETRO_pontos = 500          # PONTOS PARA ATIVAR O MODO DIFICL (DEFAULT = 500)
_L3_batidas = 5                     # BATIDAS DE CARRO (DEFAULT = 5)
_L3_falha_atender = 2               # NAO ATENDER O TELEFONE (DEFAULT = 2)

## AJUSTES - DADOS DE AJUSTE

_L3_tempo_jogo_facil = 60           # TEMPO DE JOGO PARA O MODO FACIL (DEFAULT = 60)
_L3_tempo_jogo_dificil = 40         # TEMPO DE JOGO PARA O MODO DIFICIL (DEFAULT = 40)

_L3_ponto_atender_facil = 200       # AJUSTE DE PONTOS AUMENTADO PARA ATENDER O CELULAR (DEFAULT = 200)
_L3_ponto_atender_dificil = 50      # AJUSTE DE PONTOS AUMENTADO PARA ATENDER O CELULAR (DEFAULT = 50)

_L3_tempo_extra_facil = 15          # TEMPO EXTRA AO COLETAR O BONUS DE TEMPO (DEFAULT = 15)
_L3_tempo_extra_dificil = 10        # TEMPO EXTRA AO COLETAR O BONUS DE TEMPO (DEFAULT = 10)